name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: cd TMessagesProj && chmod +x gradlew && ./gradlew assembleTMessageRelease
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: TMessagesProj/build/outputs/apk/release/*.apk
